### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by an303042** [ansemjo/diffusionbooth#1]
Very cool project!
I'm thinking of using this at my kid's upcoming birthday party, so I've set it up for myself to test and noticed some things aren't working 100% for me. 
Background: I've been using SD for a while so pretty much know my way around it, but can't code.
Anyway, it seems to me that it keeps using the same checkpoint that was last loaded into a1111 webui. In the console I don't see a different checkpoint being loaded no matter what preset I select on the frontend. Also, how can I change the denoising strength? The current results are too far off from the original images to my liking, and I would like to lower the denoising a bit.
Thanks!

**Comment by ansemjo** [comment]
Glad you like it!

1) Have you downloaded alle the models mentioned in [`models.md`](https://github.com/ansemjo/diffusionbooth/blob/c0e4bca792640046766789b9eda1d91a13bce520/models.md) and put them in the correct places, `models/Stable-diffusion/`, `models/ControlNet/` and `models/Lora/`? I've never had the behaviour you described, to be honest. Can you see the models in the dropdown in the WebUI interface?

2) You can find the preset parameters here: [`src/stablediffusion.ts#L186-L307`](https://github.com/ansemjo/diffusionbooth/blob/c0e4bca792640046766789b9eda1d91a13bce520/src/stablediffusion.ts#L186-L307). They all use the [`dif` function](https://github.com/ansemjo/diffusionbooth/blob/c0e4bca792640046766789b9eda1d91a13bce520/src/stablediffusion.ts#L138-L142) to avoid repetition. This function takes the model name, three weights for the ControlNets between 0.0 and 1.0 (this is the main method I used to obtain variable likeness) and a prompt. The denoising strength of the input image is common to all presets and is set in [line 86](https://github.com/ansemjo/diffusionbooth/blob/c0e4bca792640046766789b9eda1d91a13bce520/src/stablediffusion.ts#L86).

**Comment by an303042** [comment]
Thanks for pointing me in the right direction. I have the checkpoints but i suspect its named differently. I assumed you were working with their hashes and not filenames. I'll try renaming things and it'll probably work.
